components/Navbar.jsx
pages/login.jsx

Token saved in local storage
https://github.com/Randomlandia/frontend/assets/152235404/0fc0564d-3f94-4428-9286-db180a115da1

feat: token saved in local storage

---

pages/login.jsx

fix: login broken

---

package-lock.json
package.json
pages/login.jsx
pages/register.jsx
pages/sandias/index.jsx

Reverts Randomlandia/frontend#14

Revert "Jesica"

---

package-lock.json
package.json
pages/login.jsx
pages/register.jsx
pages/sandias/index.jsx

Reverts Randomlandia/frontend#17

Revert "Revert "Jesica""

---

components/Avatar.jsx
components/Navbar.jsx
components/modalAvatar.jsx
pages/about.jsx
pages/index.jsx
pages/login.jsx
pages/randomlandia.jsx
pages/register.jsx
pages/user/[id].jsx

feat: links , menu 
https://github.com/Randomlandia/frontend/assets/152235404/87999905-c995-4db7-a5a6-82dfda73f00c

feat: boton menu, bg menu, links secuencia

---

components/Avatar.jsx
components/Navbar.jsx
components/RandySpeechBubble.jsx
components/modalAvatar.jsx
components/modalNombre.jsx
pages/login.jsx
pages/menu/[topic].jsx
pages/register.jsx
pages/user/ackn/[topic].jsx

feat: sandia reverse
feat: change name
https://github.com/Randomlandia/frontend/assets/152235404/b36e4c7a-577a-4686-b71a-3dc9c274b97f
https://github.com/Randomlandia/frontend/assets/152235404/92f3abd1-d29f-4f23-8954-81fcec5d2932

Sandias logic

---

pages/login.jsx
pages/register.jsx

fix: campos requeridos, en registro, login y color de texto alerta}
https://github.com/Randomlandia/frontend/assets/152235404/4f0181ce-31ec-4b82-9dfd-e8e58fb0a182
https://github.com/Randomlandia/frontend/assets/152235404/0f7e4489-f3fb-4027-ba9e-21c1006fab95

Login fixx

---

components/Avatar.jsx
components/Navbar.jsx
components/SeleccionaAvatar.jsx

feat: new avatars
fix: funcion Button Avatar
https://github.com/Randomlandia/frontend/assets/152235404/c51e986c-f965-44d8-badc-91874c2c3b98

feat: nuevos avatar

---

components/Avatar.jsx
components/Navbar.jsx
components/SeleccionaAvatar.jsx

Iconos avatar

---

pages/user/[id].jsx

fix: remove id router

---

components/home/luz.jsx
pages/index.jsx
styles/globals.css

https://github.com/Randomlandia/frontend/assets/152235404/bc33febd-a86b-4ed3-8a13-cf1bdbdbdbe5

feat: prototipo chispitas

---

components/home/luz.jsx
pages/index.jsx
pages/randomlandia.jsx

Feat: button jugar Home
https://github.com/Randomlandia/frontend/assets/152235404/8d44c405-a39e-494f-ac91-c5ec1134d564

feat: boton Jugar

---

components/home/luz.jsx
pages/index.jsx
styles/globals.css

feat: Randy burbuja reverse animacion
fix: doble boton
feat: botonJugar burbuja
feat: arbol Responsive
https://github.com/Randomlandia/frontend/assets/152235404/75509538-d6c4-405a-a50f-02c5983192e9
https://github.com/Randomlandia/frontend/assets/152235404/4ca56f54-e982-4e8e-b3a2-f2249c97a124

fix: doble boton

---

components/about/cardRandyIcono.jsx
components/landing/cardNosotrosDescri.jsx
components/landing/unicos2Div.jsx
pages/about.jsx

fix:about tamaño CardRandyIcono

---

pages/about.jsx
pages/randomlandia.jsx

fix: card componente unicos por componente perspectiva
https://github.com/user-attachments/assets/a1f5ae92-bb92-4a29-aba8-255448ff80c0

fix: perspectiva State Button

---

components/Avatar.jsx
components/Navbar.jsx
pages/login.jsx
pages/register.jsx
pages/user/achv/[topic].jsx
pages/user/achv/index.jsx

feat: logros
fix: create account
fix: navar name and avatar
https://github.com/user-attachments/assets/3070301d-cc99-4150-930e-9bbab88eba1a
https://github.com/user-attachments/assets/92f58718-fa32-4395-8fd5-495bb7839f3f
https://github.com/user-attachments/assets/fc996910-70db-4261-b0a7-d55cd354a86d

Logros dos

---

components/MenuFavsCircle.jsx
components/MenuFavsSlider.jsx
components/Navbar.jsx
components/SandiaCardPreview.jsx
components/TemaContainer.jsx
pages/login.jsx
pages/register.jsx
pages/user/ackn/[topic].jsx
pages/user/favs/[topic].jsx

fix: merge
https://github.com/user-attachments/assets/e3ec8aa9-9564-4bf7-a254-54b6a9d7ebff

fix: merge

---

components/Navbar.jsx
components/home/luz.jsx
pages/index.jsx
pages/login.jsx

feat: login redirige a login para poder iniciar sesion más intuitivo

feat: home luces on musica off

---

pages/_app.js
pages/login.jsx
utils/beforeUnloadHandler.jsx
utils/logoutHandler.jsx

feat: handleUpdateUser works before unload page if isLogged.

feat: updateUser with beforeUnload

---

backups/menu/menu/index.jsx
pages/login.jsx
pages/randomlandia.jsx
pages/register.jsx

feat: respponsiv login y register, diseños gemelos
feat: avatar ya tiene tamaño visible
fix: se elimina campo fecha que estaba duplocado
https://github.com/user-attachments/assets/2c6addfe-78cb-4fd8-996d-38d0cabb634c
https://github.com/user-attachments/assets/7e70ac03-8f54-4874-be83-ae2bbf431153

feat: add resposividad, y diseño gemelo a login y register

---

pages/index.jsx
pages/user/index.jsx

feat: menu user no logeado
https://github.com/user-attachments/assets/89312647-4e9e-40c2-8fe5-e444cf778208

feat: user index animation

---

README.md
backups/modal error 404/Error404.jsx
backups/modal user name/ModalUserName.jsx
components/Avatar.jsx
components/ContactoFooter.jsx
components/Navbar.jsx
components/RandyNotFound.jsx
components/UserName.jsx
components/constants/descrip.jsx
pages/about.jsx
pages/menu/[topic].jsx
pages/user/ackn/[topic].jsx
pages/user/ackn/index.jsx
pages/user/favs/[topic].jsx
pages/user/favs/index.jsx

fix: about
